### ISSUE TITLE
Trying to get clojure-lsp working in sublimelsp/LSP

### ISSUE THREAD

**Issue by slifin** [snoe/clojure-lsp#121]
I'm trying to use clojure-lsp with https://github.com/sublimelsp/LSP this is the configuration file, that I've created to try and leverage clojure-lsp, I should say that clj-kondo is working as expected

```json
{
  "clients":
  {
    "clojure-lsp": {
      "command": ["/usr/local/bin/clojure-lsp"],
      "enabled": true,
      "languageId": "clojure",
      "scopes": [
        "source.clojure"
      ],
      "syntaxes": [
        "Packages/Clojure/Clojure.sublime-syntax"
      ]
    },
    "clj-kondo":
    {
      "command":
      [
        "java",
        "-jar",
        "/Users/adriansmith/Scripts/clj-kondo-lsp-server-2020.03.20-standalone.jar"
      ],
      "enabled": true,
      "languageId": "clojure",
      "scopes":
      [
        "source.clojure"
      ],
      "syntaxes":
      [
        "Packages/Clojure/Clojure.sublime-syntax"
      ]
    }
  }
}

```

But when I go to use clojure-lsp I don't get any functionality

<img width="491" alt="Screenshot 2020-03-31 at 15 17 23" src="https://user-images.githubusercontent.com/198857/78036926-c35f1880-7362-11ea-9a44-799b66a5eaa8.png">

The first error I got was:

```
  File "./python3.3/contextlib.py", line 48, in __enter__
  File "/Users/adriansmith/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/sessions.py", line 201, in acquire_timeout
    raise InitializeError(self)
LSP.plugin.core.sessions.InitializeError: clojure-lsp did not respond to the initialize request within 30 seconds
```

The default timeout is 3 seconds I had bumped it to 30 seconds, I imagine there's something wrong with my configuration

If I run `/usr/local/bin/clojure-lsp` directly (put there via `brew install clojure-lsp`) I get:

```
clojure-lsp
Exception in thread "main" java.lang.UnsupportedClassVersionError: clojure_lsp/ClojureExtensions has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at clojure.lang.RT.classForName(RT.java:2211)
	at clojure.lang.RT.classForNameNonLoading(RT.java:2224)
	at clojure_lsp.main$loading__6721__auto____13275.invoke(main.clj:1)
	at clojure_lsp.main__init.load(Unknown Source)
	at clojure_lsp.main__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at clojure.lang.RT.classForName(RT.java:2211)
	at clojure.lang.RT.classForName(RT.java:2220)
	at clojure.lang.RT.loadClassForName(RT.java:2239)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6839.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:384)
	at clojure.lang.Util.loadWithClass(Util.java:251)
	at clojure_lsp.main.<clinit>(Unknown Source)
```

So I tried using the installation steps on the main GitHub page and uninstalling clojure-lsp via brew with `brew uninstall clojure-lsp`

I've taken latest from the GitHub releases page and put it in /usr/local/bin with chmod 755 now I get the following error:

<img src="https://tva1.sinaimg.cn/large/00831rSTgy1gddhuf7m5xj30nc09cta7.jpg" style="zoom:33%;" />

If I change the command key to just `clojure-lsp` a file missing error occurs, (with full path the above error)

if on the terminal I run `/usr/local/bin/clojure-lsp` it hangs like I think it should, if I invoke it without the full path I get `Error: Unable to access jarfile clojure-lsp`

**Comment by slifin** [comment]
How do we solve the error "[Errno 8] Exec format error" ?

**Comment by slifin** [comment]
I cross-posted this to here: https://github.com/sublimelsp/LSP/issues/936
The solution given there worked for me, which was to change the command key to match kondo

```json
"clojure-lsp": {
      "command": ["java", "-jar", "/usr/local/bin/clojure-lsp"]
```
