### ISSUE TITLE
"/bin/sh: 0: Can't open clojure-lsp" with the latest release

### ISSUE THREAD

**Issue by daveyarwood** [snoe/clojure-lsp#151]
I used to have clojure-lsp working and integrated into my Neovim setup, and I remember being able to successfully run it from the command line as well. For some reason, the latest handful of releases don't seem to work on my machine. Neovim (coc) reports that clojure-lsp crashes repeatedly when trying to run, and when I try to run it from the command line, this happens:

```bash
$ clojure-lsp
/bin/sh: 0: Can't open clojure-lsp
```

Googling that error message didn't tell me much. Let me know if there's any other helpful info I can provide.

**Comment by ericdallo** [comment]
@daveyarwood I tested the latest binary from releases and it seems to work normally, are you sure you downloaded the latest binary from [this page](https://github.com/snoe/clojure-lsp/releases)?

**Comment by daveyarwood** [comment]
Yes.

It's weird, _all_ of the releases going back at least as far as April 2020 seem to be giving me the same result. But I think when I was using clojure-lsp successfully before, it was one of those versions. So this makes me wonder if something might be messed up with GitHub or my browser or something?

I re-tested a bunch of the releases just now, and most of the time, I got the error message above ("Can't open clojure-lsp"), but one time, when I tested the same release twice in a row, I got the aforementioned message the first time, and then a different one the second time:

```
Failed to execute process '/home/dave/bin/clojure-lsp'. Reason:
exec: Exec format error
The file '/home/dave/bin/clojure-lsp' is marked as an executable but could not be run by the operating system.
```

The above is all with Firefox. I tried the latest result again with Chrome and got the same result ("Can't open clojure-lsp").

**Comment by daveyarwood** [comment]
Aha! I forgot something that I learned months ago, which is that I can't run `clojure-lsp` from Fish shell, I have to be in a Bash shell. When I do that with the latest release, I get a bit further, but it looks like there is a Java version issue:

```
$ clojure-lsp
Exception in thread "main" java.lang.UnsupportedClassVersionError: clojure_lsp/ClojureExtensions has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at clojure.lang.RT.classForName(RT.java:2211)
        at clojure.lang.RT.classForNameNonLoading(RT.java:2224)
        at clojure_lsp.main$loading__6721__auto____13341.invoke(main.clj:1)
        at clojure_lsp.main__init.load(Unknown Source)
        at clojure_lsp.main__init.<clinit>(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at clojure.lang.RT.classForName(RT.java:2211)
        at clojure.lang.RT.classForName(RT.java:2220)
        at clojure.lang.RT.loadClassForName(RT.java:2239)
        at clojure.lang.RT.load(RT.java:449)
        at clojure.lang.RT.load(RT.java:424)
        at clojure.core$load$fn__6839.invoke(core.clj:6126)
        at clojure.core$load.invokeStatic(core.clj:6125)
        at clojure.core$load.doInvoke(core.clj:6109)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.lang.Var.invoke(Var.java:384)
        at clojure.lang.Util.loadWithClass(Util.java:251)
        at clojure_lsp.main.<clinit>(Unknown Source)
```

**Comment by daveyarwood** [comment]
...and the above was run in a directory that had a `.java-version` file pinning that project to Java 8.

I tried it again in another directory (using Java 11), and it worked.

**Comment by ericdallo** [comment]
yeah, java v55 is from JDK 11 I think, @snoe do you compile `clojure-lsp` with what version of JDK?

**Comment by snoe** [comment]
It's built on circle using the clojure/lein-2.9.1 image which seems to use jdk11 -- makes sense to try to use a jdk8 image.

https://github.com/snoe/clojure-lsp/blob/master/.circleci/config.yml
https://hub.docker.com/layers/clojure/library/clojure/lein-2.9.1/images/sha256-719af2315ed79ae87b636f53669e2dc27e828191dfa2da7096c5bac5b245af88?context=explore

**Comment by snoe** [comment]
@daveyarwood can you try the latest release, should be built with jdk8?

**Comment by daveyarwood** [comment]
I can confirm it's fixed in the latest release. Thanks! :+1:
