### ISSUE TITLE
Fail to update brew formula

### ISSUE THREAD

**Issue by netpyoung** [snoe/clojure-lsp#63]
I wrote MR - https://github.com/Homebrew/homebrew-core/pull/43293/files
But fail to test on ci.

When I install a formula like that, It is works.
```
$ brew install Formula/clojure-lsp.rb
==> Downloading https://homebrew.bintray.com/bottles/clojure-lsp-20190614T052638.mojave.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "clojure-lsp"
Download failed: https://homebrew.bintray.com/bottles/clojure-lsp-20190614T052638.mojave.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://github.com/snoe/clojure-lsp/archive/release-20190614T052638.tar.gz
Already downloaded: /Users/pyoung/Library/Caches/Homebrew/downloads/98e88c32d18bc736fb67444007623dde96b17ae0145e4060d2a0c8444fb3eca3--clojure-lsp-release-20190614T052638.tar.gz
==> lein uberjar
🍺  /usr/local/Cellar/clojure-lsp/20190614T052638: 6 files, 30.8MB, built in 23 seconds
```

but when I try like that, I got a exception like CI.
```
$ wget https://github.com/snoe/clojure-lsp/archive/release-20190614T052638.tar.gz
$ tar zxvf release-20190614T052638.tar.gz
$ cd clojure-lsp-release-20190614T052638
$ lein uberjar
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Retrieving com/jakemccrary/lein-test-refresh/0.23.0/lein-test-refresh-0.23.0.pom from clojars
Retrieving jakemcc/clojure-gntp/0.1.1/clojure-gntp-0.1.1.pom from clojars
Retrieving lein-binplus/lein-binplus/0.6.5/lein-binplus-0.6.5.pom from clojars
Retrieving de/ubercode/clostache/clostache/1.4.0/clostache-1.4.0.pom from clojars
Retrieving org/clojure/core.incubator/0.1.2/core.incubator-0.1.2.pom from central
Retrieving clj-zip-meta/clj-zip-meta/0.1.3/clj-zip-meta-0.1.3.pom from clojars
Retrieving funcool/octet/1.1.2/octet-1.1.2.pom from clojars
Retrieving io/netty/netty-buffer/4.1.30.Final/netty-buffer-4.1.30.Final.pom from central
Retrieving io/netty/netty-parent/4.1.30.Final/netty-parent-4.1.30.Final.pom from central
Retrieving io/netty/netty-common/4.1.30.Final/netty-common-4.1.30.Final.pom from central
Retrieving org/clojure/clojure/1.4.0/clojure-1.4.0.jar from central
Retrieving org/clojure/core.incubator/0.1.2/core.incubator-0.1.2.jar from central
Retrieving io/netty/netty-common/4.1.30.Final/netty-common-4.1.30.Final.jar from central
Retrieving io/netty/netty-buffer/4.1.30.Final/netty-buffer-4.1.30.Final.jar from central
Retrieving com/jakemccrary/lein-test-refresh/0.23.0/lein-test-refresh-0.23.0.jar from clojars
Retrieving jakemcc/clojure-gntp/0.1.1/clojure-gntp-0.1.1.jar from clojars
Retrieving de/ubercode/clostache/clostache/1.4.0/clostache-1.4.0.jar from clojars
Retrieving clj-zip-meta/clj-zip-meta/0.1.3/clj-zip-meta-0.1.3.jar from clojars
Retrieving lein-binplus/lein-binplus/0.6.5/lein-binplus-0.6.5.jar from clojars
Retrieving funcool/octet/1.1.2/octet-1.1.2.jar from clojars
Retrieving funcool/clojure.jdbc/0.9.0/clojure.jdbc-0.9.0.pom from clojars
Retrieving com/taoensso/tufte/2.0.1/tufte-2.0.1.pom from clojars
Retrieving com/taoensso/encore/2.94.0/encore-2.94.0.pom from clojars
Retrieving org/clojure/tools.reader/1.2.1/tools.reader-1.2.1.pom from central
Retrieving org/eclipse/lsp4j/org.eclipse.lsp4j/0.4.0/org.eclipse.lsp4j-0.4.0.pom from central
Retrieving org/eclipse/lsp4j/org.eclipse.lsp4j.generator/0.4.0/org.eclipse.lsp4j.generator-0.4.0.pom from central
Retrieving org/eclipse/lsp4j/org.eclipse.lsp4j.jsonrpc/0.4.0/org.eclipse.lsp4j.jsonrpc-0.4.0.pom from central
Retrieving medley/medley/1.0.0/medley-1.0.0.pom from clojars
Retrieving trptcolin/versioneer/0.2.0/versioneer-0.2.0.pom from clojars
Retrieving org/eclipse/xtend/org.eclipse.xtend.lib/2.13.0/org.eclipse.xtend.lib-2.13.0.pom from central
Retrieving org/eclipse/xtext/org.eclipse.xtext.xbase.lib/2.13.0/org.eclipse.xtext.xbase.lib-2.13.0.pom from central
Retrieving org/eclipse/xtend/org.eclipse.xtend.lib.macro/2.13.0/org.eclipse.xtend.lib.macro-2.13.0.pom from central
Retrieving com/google/guava/guava/19.0/guava-19.0.pom from central
Retrieving com/google/guava/guava-parent/19.0/guava-parent-19.0.pom from central
Retrieving org/xerial/sqlite-jdbc/3.21.0.1/sqlite-jdbc-3.21.0.1.pom from central
Retrieving log4j/log4j/1.2.17/log4j-1.2.17.pom from central
Retrieving org/clojure/core.async/0.4.474/core.async-0.4.474.pom from central
Retrieving org/clojure/tools.analyzer.jvm/0.7.0/tools.analyzer.jvm-0.7.0.pom from central
Retrieving org/eclipse/lsp4j/org.eclipse.lsp4j.generator/0.4.0/org.eclipse.lsp4j.generator-0.4.0.jar from central
Retrieving org/eclipse/lsp4j/org.eclipse.lsp4j/0.4.0/org.eclipse.lsp4j-0.4.0.jar from central
Retrieving org/eclipse/lsp4j/org.eclipse.lsp4j.jsonrpc/0.4.0/org.eclipse.lsp4j.jsonrpc-0.4.0.jar from central
Retrieving org/eclipse/xtend/org.eclipse.xtend.lib/2.13.0/org.eclipse.xtend.lib-2.13.0.jar from central
Retrieving com/google/guava/guava/19.0/guava-19.0.jar from central
Retrieving org/xerial/sqlite-jdbc/3.21.0.1/sqlite-jdbc-3.21.0.1.jar from central
Retrieving log4j/log4j/1.2.17/log4j-1.2.17.jar from central
Retrieving org/eclipse/xtext/org.eclipse.xtext.xbase.lib/2.13.0/org.eclipse.xtext.xbase.lib-2.13.0.jar from central
Retrieving org/eclipse/xtend/org.eclipse.xtend.lib.macro/2.13.0/org.eclipse.xtend.lib.macro-2.13.0.jar from central
Retrieving org/clojure/core.async/0.4.474/core.async-0.4.474.jar from central
Retrieving org/clojure/tools.analyzer.jvm/0.7.0/tools.analyzer.jvm-0.7.0.jar from central
Retrieving com/taoensso/encore/2.94.0/encore-2.94.0.jar from clojars
Retrieving medley/medley/1.0.0/medley-1.0.0.jar from clojars
Retrieving trptcolin/versioneer/0.2.0/versioneer-0.2.0.jar from clojars
Retrieving com/taoensso/tufte/2.0.1/tufte-2.0.1.jar from clojars
Retrieving funcool/clojure.jdbc/0.9.0/clojure.jdbc-0.9.0.jar from clojars
Compiling 1 source files to /Users/pyoung/remove-it/clojure-lsp-release-20190614T052638/target/classes
Compiling clojure-lsp.clojure-core
Compiling clojure-lsp.crawler
Compiling clojure-lsp.db
Compiling clojure-lsp.handlers
java.lang.SecurityException: class "org.eclipse.lsp4j.TextDocumentIdentifier"'s signer information does not match signer information of other classes in the same package, compiling:(interop.clj:1:1)
Exception in thread "main" java.lang.SecurityException: class "org.eclipse.lsp4j.TextDocumentIdentifier"'s signer information does not match signer information of other classes in the same package, compiling:(interop.clj:1:1)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3700)
	at clojure.lang.Compiler.compile1(Compiler.java:7609)
	at clojure.lang.Compiler.compile1(Compiler.java:7599)
	at clojure.lang.Compiler.compile(Compiler.java:7676)
	at clojure.lang.RT.compile(RT.java:413)
	at clojure.lang.RT.load(RT.java:458)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:1789)
	at clojure_lsp.handlers$loading__6434__auto____11105.invoke(handlers.clj:1)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3695)
	at clojure.lang.Compiler.compile1(Compiler.java:7609)
	at clojure.lang.Compiler.compile1(Compiler.java:7599)
	at clojure.lang.Compiler.compile(Compiler.java:7676)
	at clojure.lang.RT.compile(RT.java:413)
	at clojure.lang.RT.load(RT.java:458)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$compile$fn__6553.invoke(core.clj:6056)
	at clojure.core$compile.invokeStatic(core.clj:6056)
	at clojure.core$compile.invoke(core.clj:6048)
	at user$eval164$fn__173.invoke(form-init7040245282839369539.clj:1)
	at user$eval164.invokeStatic(form-init7040245282839369539.clj:1)
	at user$eval164.invoke(form-init7040245282839369539.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.lang.SecurityException: class "org.eclipse.lsp4j.TextDocumentIdentifier"'s signer information does not match signer information of other classes in the same package
	at java.base/java.lang.ClassLoader.checkCerts(ClassLoader.java:1155)
	at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:910)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1019)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:823)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:721)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:644)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1021)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:823)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:721)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:644)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:580)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:580)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:580)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:580)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:580)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:580)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:580)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:580)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:416)
	at clojure.lang.RT.classForName(RT.java:2204)
	at clojure.lang.RT.classForNameNonLoading(RT.java:2217)
	at clojure_lsp.interop$loading__6434__auto____11649.invoke(interop.clj:1)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3695)
	... 61 more
Compilation failed: Subprocess failed
```

**Comment by chenrui333** [comment]
@netpyoung, is this still an issue for you. If that is the case, feel free to submit in the homebrew-core side, and tag me as well. Thanks!

**Comment by netpyoung** [comment]
oh I forget this, I close this issue, you already update that formula! thank you.

**Comment by chenrui333** [comment]
Cool!
